services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

    # healthcheck removed for debugging

  inventoryservice:
    build: .
    # depends_on removed to allow app to start regardless of SQL Server healthcheck
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ProjectsDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
    ports:
      - "8080:80"
